<?php

	// Load the data helper class
	$data = $this->helper ("JetRails\Varnish\Helper\Data");
	// If the module is disabled, then don't show the controls
	if ( !$data->isEnabled () ) return;

?>
<div class="varnish-cache-management" >
	<h2>Varnish Cache™ Management</h2>
	<form method="post" action="<?= $block->getUrl ('varnish/purge/url') ?>" >
		<span>Purge By URL:</span>
		<input type="text" placeholder="URL" name="url" />
		<button type="submit" ><span>Purge</span></button>
		<br>
		<select name="type" class="admin__control-select add-left-space" >
			<option value="exact" selected="selected" >Exact Match</option>
			<option value="substring" >Sub-String</option>
		</select>
	</form>
	<form method="post" action="<?= $block->getUrl ('varnish/purge/store') ?>" >
		<span>Purge By Store:</span>
		<select name="id" class="admin__control-select" >
			<?php foreach ( $data->getStoreViews () as $storeView ): ?>
				<option value="<?= $storeView->id ?>" ><?= $storeView->name ?></option>
			<?php endforeach ?>
		</select>
		<button type="submit" ><span>Purge</span></button>
	</form>
	<form method="post" action="<?= $block->getUrl ('varnish/purge/all') ?>" >
		<span style="margin-right: 324px;" >Purge All:</span>
		<button type="submit" ><span>Purge</span></button>
	</form>
	<span class="disclaimer" >Varnish is a registered trademark of Varnish Software AB and its affiliates.</span>
</div>
